package com.Framwork.enums;

public enum ConfigProperties {
	URL,
	OVERRIDEREPORTS,
	PASSEDSTEPSSCREENSHOTS,
	FAILEDSTEPSSCREENSHOTS,
	SKIPPEDSTEPSSCREENSHOTS,
	RETRYFAILEDTESTS,
	RUNMODE,
	BROWSER;

}
