package com.Framwork.enums;

public enum ConfigProperties {
	URL,
	USERNAME,
	PASSWORD,
	OVERRIDEREPORTS,
	PASSEDSTEPSSCREENSHOTS,
	FAILEDSTEPSSCREENSHOTS,
	SKIPPEDSTEPSSCREENSHOTS,
	RETRYFAILEDTESTS,
	RUNMODE,
	SELENIUMGRIDURL,
	BROWSER;
	

}
